version: '3.9'
services:
  web:
    depends_on:
      - automatisation
      - API_s
    ports:
      - 8001:8001
    env_file:
      - cinapps/.env
    build:
      context: ./cinapps/   # Chemin ajusté pour correspondre au nom de l'application
      dockerfile: Dockerfile
    volumes:
      - ./cinapps/:/app/
  automatisation:
    build:
      context: ./automatisation/
      dockerfile: Dockerfile   
    # Ajoutez d'autres configurations nécessaires pour votre cron job ici
    # Par exemple, montez les fichiers de configuration, définissez des variables d'environnement, etc.
  API_s:
    ports:
      - 8002:8002
    build:
      context: ./API_s/
      dockerfile: Dockerfile